apiVersion: v1
kind: Service
metadata:
  name: book-tracker-service
spec:
  selector:
    app: book-tracker-service
  ports:
    - port: 80
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-tracker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-tracker-service
  template:
    metadata:
      labels:
        app: book-tracker-service
    spec:
      containers:
        - name: book-tracker-service
          image: anushasankaranarayanan/book-tracker-service:1.0.0
          ports:
            - containerPort: 9000
          env:
            - name: LOG_LEVEL
              value: info
            - name: SERVER_PORT
              value: "9000"
            - name: NAME
              value: book-tracker-service
            - name: COUCHBASE_HOST
              value: <couchbase-host>
            - name: COUCHBASE_BUCKET
              value: reading-list
            - name: COUCHBASE_USER
              value: <username>
            - name: COUCHBASE_PASSWORD
              value: <password>
            - name: ENABLE_DB_VERBOSE_LOGGING
              value: "false"
          imagePullPolicy: Always